name: Github Actions
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.0
      - name: Jest packages installation
        run: npm install jest @jest/globals
      - name: Run tests
        run: npm run test
